echo off
echo (Re-)Generating all report figures and tables...
echo Intro assignments...
cd "..\intro\"
py analysis.py
echo Assignment 1...
cd "..\assignment_1\"
@REM py analysis.py # no analysis.py file yet
echo Done!